### ISSUE TITLE
Custom expansion icons

### ISSUE THREAD

**Issue by KidneyForDinner** [zaffudo/CAH-Generator#2]
Could you add an option for using a custom jpeg file as an expansion icon? It would make it easier to tell custom cards apart from official ones.

**Comment by SeanFromIT** [comment]
+1

**Comment by SXRWahrheit** [comment]
+1

**Comment by SXRWahrheit** [comment]
I see that you use pre-generated card images. Could you provide a PSD in the github project such that we can generate our own card images, and add support to upload them for use via the tool?

**Comment by zaffudo** [comment]
I'm resisting this project, and will look into using custom images for the expansion icon. 

Unfortunately, I don't have PSD's of the card images - I created them in ImageMagick the same way I create the cards from the custom text entered. I only use the pre-generated ones in the tool to save on processing time for the site.

**Comment by SXRWahrheit** [comment]
Revisiting, not resisting, yeah?

**Comment by zaffudo** [comment]
Yeah - damn auto-correct!

**Comment by SXRWahrheit** [comment]
Cool. I look forward to the (potential) new feature - this would make for some even cooler custom sets!

**Comment by SXRWahrheit** [comment]
Any luck with this? Looking to make a new set soon, would love to use a custom icon.

**Comment by kasekesy** [comment]
can you plzzzzzzzzzzzz update this to include all of the missing icons, expansion 5 and 6, 90s, table top, aussie, UK, retail mini, science pack, food pack, fantasy, world wide web, bug out bag, opening the safe, target retail pack, Hilary and trump packs, fascism pack, star of david and any other holiday missing one more I think

**Comment by zaffudo** [comment]
No real progress as of yet - in truth I've barely looked at as work has picked up recently. The cards being at 1200dpi was probably a bit of overkill and requires that the icons need to be about 125x125 to print well, and my ImageMagick acumen is going to make validating, rotating, aligning, etc custom images very slow going.  

@SXRWahrheit - It's doubtful I'll have the custom image ability available quickly. If you've got an icon you want me to add to the existing architecture, shoot me a link to it and I'll get it added so you can generate your set.

@kasekesy - Having no artistic talent, I really have no way of getting icons for existing packs at that size (almost all of the ones currently in use on the site for existing packs were provided for me by folks from reddit).

**Comment by zaffudo** [comment]
Turns out this wasn't as daunting as I remembered it being. It could definitely be more feature rich, and definitely could use some more testing, but the basic ability to do custom icons has been added.

**Comment by SXRWahrheit** [comment]
So awesome. Thank you!
