### ISSUE TITLE
French accents

### ISSUE THREAD

**Issue by felixbrabant** [zaffudo/CAH-Generator#3]
Accents (such as é è à ù - we use them a lot in french) are not displaying on the generated cards.

**Comment by shirizaan** [comment]
The post content needs to be utf-8 encoded similar to this:

htmlentities($_POST['text1'], ENT_QUOTES, "UTF-8");

**Comment by ahter** [comment]
Turkish characters (such as ş, ç, ğ, ü etc) do not work either. I couldn't make it work.

**Comment by aemitis** [comment]
I have the same issue as I'm trying to write in Portuguese. Can anyone make this fix?

**Comment by brunoamaral** [comment]
I took a quick look at the code and this seems to be the solution as suggested by @mlapaglia https://github.com/brunoamaral/CAH-Generator/commit/e9f766a456827d4024c066ead266256e244418fd

It needs to be tested. If someone could give me feedback on whether this works I would appreciate it :)

**Comment by zaffudo** [comment]
Should hopefully be fixed in master, and on the live site.

**Comment by aemitis** [comment]
It's working correctly! Thanks!
